---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-install-httpd"
      label: "Install Httpd"
      solveButton: false
    - name: "02-position"
      label: "Position"
      solveButton: false
    - name: "03-run"
      label: "Run"
      solveButton: false
    - name: "04-build"
      label: "Build"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
  - name: "Clumsy Bird"
    url: http://webapp-${guid}.${domain}/clumsy-bird
    modules:
      - "04-build"
  - name: "Website"
    url: http://webapp-${guid}.${domain}/
    modules:
      - "03-run"
      - "04-build"
  - name: "RHEL Web Console"
    url: https://cockpit-${guid}.${domain}/
    modules:
      - "02-position"