---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: webapp
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: webapp
      - name: cockpit
        ports:
          - port: 9090
            protocol: TCP
            targetPort: 9090
            name: webapp
    routes:
      - name: webapp
        host: webapp
        service: webapp
        targetPort: 80
        tls: true
        tls_termination: Edge
      - name: cockpit
        host: cockpit
        service: cockpit
        targetPort: 9090
        tls: true
        tls_termination: Edge